import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { DirectionProvider } from "@/components/ui/direction";
import { Noto_Sans_Arabic } from "next/font/google";
import HeaderUi from "@/components/header/header-ui";
import FooterUi from "@/components/footer/footer-ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = Noto_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${fontSans.variable} h-full`}
      suppressHydrationWarning
    >
      <body className="h-full">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DirectionProvider dir="rtl" direction="rtl">
            <div className="">
              <HeaderUi />
              <main className="p-4 max-w-7xl mx-auto mt-16 md:mt-24 lg:mt-0">
                {children}
              </main>
              <FooterUi />
            </div>
          </DirectionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
