import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { DirectionProvider } from "@/components/ui/direction";
import { Noto_Sans_Arabic } from "next/font/google";
import HeaderUi from "@/components/header/header-ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = Noto_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={fontSans.variable}
      suppressHydrationWarning
    >
      <body className="">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DirectionProvider dir="rtl" direction="rtl">
            <HeaderUi />
            <main className="p-4 max-w-7xl mx-auto">{children}</main>
            <footer>d</footer>
          </DirectionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
