import ProfNavigation from "@/components/profile/navigation";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-12 gap-4">
      <ProfNavigation />
      <div className="col-span-12 order-1 lg:order-2 lg:col-span-9">
        {children}
      </div>
    </div>
  );
}
